apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql-chart.fullname" . }}
  labels:
    {{ include "mysql-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "mysql-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "mysql-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mysql-chart.serviceAccountName" . }}

      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.env.mysqlrootpw }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.env.mysqldb }}"
            - name: MYSQL_USER
              value: "{{ .Values.env.mysqluser }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.env.mysqlpass }}"

          ports:
            - containerPort: 3306
              protocol: TCP

{{ with .Values.resources }}
          resources:
{{ toYaml . | nindent 12 }}
{{ end }}

{{ with .Values.volumeMounts }}
          volumeMounts:
{{ toYaml . | nindent 12 }}
{{ end }}

{{ with .Values.volumes }}
      volumes:
{{ toYaml . | nindent 8 }}
{{ end }}

