apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app
  labels:
    app: two-tier

spec:
  containers:
    - name: two-tier-app-ctr
      image: trainwithshubham/flaskapp:latest
      env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_DB
          value: "myDb"
      ports:
        - containerPort: 5000
      imagePullPolicy: Always
